apiVersion: v1
kind: Namespace
metadata:
  name: webcolor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor
  namespace: webcolor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webcolor
  template:
    metadata:
      labels:
        app: webcolor
    spec:
      containers:
      - name: webcolor
        image: fabricioveronez/web-color:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webcolor-svc-cip
  namespace: webcolor
spec:
  selector:
    app: webcolor
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webcolor-svc-np
  namespace: webcolor
spec:
  selector:
    app: webcolor
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082 
  type: NodePort

